server:
  port: 9411
  
spring:
  application:
    name: zipkin
  cloud:
    config:
      name: zipkin
      discovery:
        service-id: config
        enabled: true
        username: admin	
        password: admin
        
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
   region: default
   registryFetchIntervalSeconds: 5
   
logging:
  level:
    org.springframework.web: DEBUG