server:
  port: 8075
  
spring:
  application:
    name: zuul

eureka:
  client:
    serviceurl:
      defaultzone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    cliente:
      path: /clientes/v1/**
      serviceId: CLIENTE
    frete:
      path: /fretes/v1/**
      serviceId: FRETE
    produto:
      path: /produtos/v1/**
      serviceId: PRODUTO
    suporte:
      path: /suportes/v1/**
      serviceId: SUPORTE